version: 0.2

env:
  variables:
    source_path: "engagement/email"
    artifact_name: "lambda-email"
    s3_bucket_name: "whiskerlabs-buildrepository"
    s3_bucket_directory: "engage/email"
            
phases:
  install:
    commands:
      - echo "Installing zip..."
      - wget http://mirrors.kernel.org/ubuntu/pool/main/z/zip/zip_3.0-8_amd64.deb
      - sudo dpkg -i zip_3.0-8_amd64.deb
      - echo "Installing virtualenv, upgrading pip"
      - python2.7 -m pip install virtualenv
      - pip install --upgrade pip
  pre_build:
    commands:
      - cd $source_path
      - virtualenv --python=python2.7 venv
      - venv/bin/pip install -r compilation/requirements.txt
      - venv/bin/pip install semver
      - venv/bin/python nextbuildver.py --bucket_name=$s3_bucket_name --bucket_dir=$s3_bucket_directory --artifact_name=$artifact_name
      - next_ver=`venv/bin/python nextbuildver.py --bucket_name=$s3_bucket_name --bucket_dir=$s3_bucket_directory --artifact_name=$artifact_name`
      - echo "Got next_ver=$next_ver"
  build:
    commands:
      - echo "Zipping dependencies"
      - cd venv/lib/python2.7/site-packages && zip --quiet -9 --recurse-paths ../../../../$artifact_name.zip *
      - cd ../../../..
      - zip --show-files $artifact_name | tail
      - echo "Adding lambda"
      - cd ./compilation
      - zip -9 ../$artifact_name.zip lambda_function.py
      - cd ..
      - zip --show-files $artifact_name | tail
      - echo "\$artifact_name=$artifact_name"
      - ls $artifact_name*
      - #mv $artifact_name.zip "`venv/bin/python nextbuildver.py "$artifact_name"`.zip"
      - echo "Have next_ver=$next_ver"
      - mv $artifact_name.zip $next_ver.zip
  post_build:
    commands:
      - echo "Copying to S3 build repo $s3_bucket"
      - # cp $artifact_name* s3.....
