version: 0.2

env:
  variables:
    source_path: "./engagement/email"
    artifact_name: "lambda-email"
    s3_bucket_name: "whiskerlabs-buildrepository"
    s3_bucket_directory: "engage/email"
            
phases:
  install:
    commands:
      - echo "Installing zip..."
      - wget http://mirrors.kernel.org/ubuntu/pool/main/z/zip/zip_3.0-8_amd64.deb
      - sudo dpkg -i zip_3.0-8_amd64.deb
      - echo "Installing virtualenv, upgrading pip"
      - python2.7 -m pip install virtualenv
      - pip install --upgrade pip
  pre_build:
    commands:
      - pwd && echo "source_path=$source_path" && ls -R $sourcepath && ls -R
      - cd $source_path && virtualenv --python=python2.7 venv
      - cd $source_path && venv/bin/pip install -r compilation/requirements.txt
      - cd $source_path && venv/bin/pip install semver
  build:
    commands:
      - echo "Zipping dependencies"
      - cd $source_path/venv/lib/python2.7/site-packages && zip --quiet -9 --recurse-paths ../../../../$artifact_name *
      - cd $source_path && zip --show-files $artifact_name | tail
      - echo "Adding lambda"
      - cd $source_path && zip -9 $artifact_name lambda.py
      - cd $source_path && mv $artifact_name `sh ./nextbuildver.sh "$artifact_name"`.zip
  post_build:
    commands:
      - echo "Copying to S3 build repo $s3_bucket"
      - # cp $artifact_name* s3.....
